SRC += muse.c

UNICODEMAP_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
ENCODER_ENABLE = yes
MIDI_ENABLE = no            # MIDI controls
AUDIO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
